# -*- coding: utf-8 -*-
"""Preparing a Data set.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_p4x6ek2997k53Wy3UOTjinDBnso-DOk

# Getting Data Set.
"""

# !wget http://mlg.ucd.ie/files/datasets/bbc-fulltext.zip

"""# Unzip the BBC folder in a directory named bbc"""

# !unzip bbc-fulltext.zip -d bbc

"""# Prepare Training Example"""

import os
import pandas as pd

# define data frame
df = pd.DataFrame()
# mapping for dictionary
# mapping class name or label name in reference to the file name
mapping = {}

# file path to the classes.
source_path = 'bbc/bbc/'

# 5 directory [ business, entertainment, politics, sport, tech ] this will be our classes
# https://www.tutorialspoint.com/python/os_listdir.htm
# https://www.guru99.com/python-check-if-file-exists.html#3


dirs = os.listdir(source_path)

for files in sorted(dirs):
  print(files)
  # chcek if it is directory or a file
  if os.path.isdir(source_path+files):
    # business = 001.txt
    mapping[files] = sorted(os.listdir(source_path+files))[:500] # doing it for first 500 .txt file

print(mapping)

mapping.keys()

"""We will need label and data file.

Label = keys

data = values/ txt file. 
"""

label = []
data = []

for key, values in mapping.items():
  print(key,values)
  for text_file in values:
    label.append(key)
    # read the content and remove the new line characters and stuff.
    data.append(open(source_path+key+"/"+text_file,encoding='cp1252').read().replace('\n'," "))

data[:3]

# label[:2000]

df['label'] = label
df['data'] = data

df.head(10)

# reshuffle the data to create a better data set
df = df.sample(frac=1).reset_index(drop=True)

df.head(10)

"""# save to csv"""

df.to_csv('train.csv',index = False, header=False)

heading_list = ['Label','Data']
df = pd.read_csv('train.csv',names=heading_list)

df